'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Hangman.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bakgrunn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bakgrunn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bakgrunn2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bakgrunn2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property clap() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("clap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property click1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("click1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Hangman0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hangman0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Hangman1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hangman1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Hangman2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hangman2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Hangman3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hangman3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Hangman4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hangman4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Hangman5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hangman5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property intro() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("intro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to admiral
        '''aften
        '''akt
        '''alaltan
        '''ammalgam
        '''anorakk
        '''aroma
        '''arrasjett
        '''asparges
        '''asyl
        '''atlas
        '''atom
        '''avlavløp
        '''åkåker
        '''ånd
        '''ånde
        '''åpning
        '''åre
        '''balje
        '''balkong
        '''ball
        '''ballett
        '''balsam
        '''bamse
        '''banan
        '''banjo
        '''bark
        '''barm
        '''barsel
        '''bart
        '''basseng
        '''bataljon
        '''batteri
        '''baug
        '''bavian
        '''båt
        '''bær
        '''beger
        '''bekken
        '''belg
        '''betennelse
        '''bibel
        '''bihule
        '''binne
        '''bjelke
        '''bjelle
        '''blære
        '''blei
        '''bleie
        '''blekk
        '''blemme
        '''blest
        '''blink
        '''blod
        '''bluse
        '''blyant
        '''boble
        '''bog
        '''boms
        '''bonus
        '''bor
        '''borg
        '''bøddel
        '''bølge
        '''bøtte
        '''bøye
        '''bram
        '''brask
        '''bråte
        '''bresj
        '''bret [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property ordliste_random() As String
            Get
                Return ResourceManager.GetString("ordliste_random", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property tap() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("tap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property tavle() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("tavle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
